### PR TITLE
Fix compatibility info, release 1.2.1

### PR DESCRIPTION
**Pull request by michael-e**

### CODE REVIEW

**Comment by nitriques** [comment]
I am happy if you pull this in :) Should it be released as well ?

**Comment by michael-e** [comment]
I won't pull this in, because I sent the request. I am a fan on the four-eye-principle.

> Should it be released as well ?

I think so, yes. When it is pulled, we should also update master.

**Comment by nitriques** [comment]
> I am a fan on the four-eye-principle.

Me too! That's why I checked it and just pulled it :smile:

**Comment by nitriques** [comment]
Should I rebase integration before pulling into master ?

**Comment by nitriques** [comment]
And I'd like to amend your commit, since it's 1.21, not 1.2.1 :smile:

**Comment by michael-e** [comment]
Shouldn't be necessary, because it is simply one commit ahead of master.

**Comment by nitriques** [comment]
> Shouldn't be necessary, because it is simply one commit ahead of master.

Well it still made a merge commit... and as I just said, the commit message is wrong :P

**Comment by michael-e** [comment]
I don't think that one can correct my stupid commit message without messing things up. History will always remember from now on. :-(

**Comment by nitriques** [comment]
> I don't think that one can correct my stupid commit message without messing things up

I sure can do!

```
git rebase -i 357496e
# amend the commit message
git push origin integration --force
```

And we won't loos anything

**Comment by michael-e** [comment]
Ah, using "the force" it is possible, of course. But I never dare to do this on public repos, because other people might have problems with that. You are basically destroying history if you `--force`.

I don't mind the merge, BTW. But changing the commit message might indeed be a good idea in this case.

Sorry for the inconvenience.

**Comment by nitriques** [comment]
> You are basically destroying history if you --force.

Nope, history is still preserved: The new commit is still related to the old one with the commit message and the commit is still in the .git directory: just not in the tree anymore.

Using --force on public repro should always be avoided when possible. When in master branch, it should be avoided at all cost since it break git pull. But on a integration branch, when both of us are the only one which will have a broken git pull, I do not find it that dangerous.

> Sorry for the inconvenience.

No worries.

**Comment by nitriques** [comment]
All done.

**Comment by michael-e** [comment]
I was on my way to push the lost (1.21) tag, but now I've seen that you did it in the meantime.

Thanks a lot, @nitriques!

**Comment by nitriques** [comment]
My pleasure !

**Pull request merged**
